Added scrolling to subscription view.
rapid7/graphql-playground pull request #2
Opened 2020-02-27 16:14 UTC by omaruszczak-r7

Fixes #.

Currently it's not possible to see the latest result of subscription if there are too many. 
- 

- 

-

2020-02-27 16:21 UTC, rwilliams-r7 commented on packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts
> -export interface CsrfHeader {
??

2020-02-27 16:25 UTC, erran-r7 requested changes

2020-02-27 16:25 UTC, erran-r7 commented on packages/graphql-playground-react/src/components/Playground/EditorWrapper.tsx
> -export class Container extends React.PureComponent {
Revert all non-CSS changes.

2020-02-27 16:25 UTC, erran-r7 commented on packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts
> +          log(err)
Strip out all non-css changes please. Looks like a conflict merge/rebasing after the upgrade to Apollo's branch of playground.

2020-02-27 17:08 UTC, erran-r7 approved these changes

2020-02-27 17:10 UTC, erran-r7 commented
Let's do a squash & merge for this PR 😄

2020-02-28 16:23 UTC, erran-r7 approved these changes

2020-03-02 10:40 UTC, merged